-- Create a table for public profiles link to auth.users
create table profiles (
  id uuid references auth.users not null primary key,
  name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on profiles
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for daily prayers
create table prayers (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  date date not null,
  fajr boolean default false,
  zuhr boolean default false,
  asr boolean default false,
  maghrib boolean default false,
  isha boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, date)
);

-- Enable RLS on prayers
alter table prayers enable row level security;

create policy "Users can view own prayers." on prayers
  for select using (auth.uid() = user_id);

create policy "Users can insert own prayers." on prayers
  for insert with check (auth.uid() = user_id);

create policy "Users can update own prayers." on prayers
  for update using (auth.uid() = user_id);

-- Create a table for daily Islamic content (Admin managed or fetched)
create table daily_content (
  id bigint generated by default as identity primary key,
  date date unique not null,
  ayah text,
  ayah_reference text,
  hadith text,
  quran_audio_url text,
  surah_name text,
  reciter text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on daily_content
alter table daily_content enable row level security;

create policy "Daily content is viewable by everyone." on daily_content
  for select using (true);

-- (Optional) If you want admin-only insert, you'd add a policy here, 
-- but normally specific admins or service_role handles content.

-- Function to handle new user profile creation automatically
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, name)
  values (new.id, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
