-- Create table for achievement definitions
CREATE TABLE IF NOT EXISTS achievements (
  id text PRIMARY KEY, -- e.g., 'first_step', 'streak_7', 'high_five'
  name text NOT NULL,
  description text NOT NULL,
  icon text NOT NULL, -- Emoji or URL
  tier text DEFAULT 'bronze', -- bronze, silver, gold, platinum
  secret boolean DEFAULT false, -- If true, description is hidden until unlocked
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for achievements (Public Read Only)
ALTER TABLE achievements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Achievements are viewable by everyone." ON achievements
  FOR SELECT USING (true);


-- Create table for user unlocked achievements
CREATE TABLE IF NOT EXISTS user_achievements (
    id bigint generated by default as identity primary key,
    user_id uuid REFERENCES auth.users NOT NULL,
    achievement_id text REFERENCES achievements(id) NOT NULL,
    unlocked_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    unique(user_id, achievement_id)
);

-- Enable RLS for user_achievements
ALTER TABLE user_achievements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own achievements." ON user_achievements
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own achievements." ON user_achievements
  FOR INSERT WITH CHECK (auth.uid() = user_id);
  
-- Allow viewing other's public profile achievements (if profile is public) - optional, for now just own.

-- Seed Initial Achievements
INSERT INTO achievements (id, name, description, icon, tier) VALUES
('first_step', 'First Step', 'Complete your first prayer log.', '🌱', 'bronze'),
('high_five', 'Perfect Day', 'Complete all 5 prayers in a single day.', '🌟', 'silver'),
('qada_payoff', 'Debt Repayer', 'Repay your first Qada prayer.', '💳', 'bronze'),
('streak_3', 'Consistency is Key', 'Maintain a 3-day prayer streak.', '🔥', 'silver'),
('streak_7', 'Week Warrior', 'Maintain a 7-day prayer streak.', '🏆', 'gold'),
('early_bird', 'Fajr Champion', 'Log Fajr on time 5 days in a row.', '🌅', 'silver')
ON CONFLICT (id) DO NOTHING;
