export const surahs = [
    { number: 1, name: "Al-Fatihah", english: "The Opener", ayahs: 7, type: "Meccan" },
    { number: 2, name: "Al-Baqarah", english: "The Cow", ayahs: 286, type: "Medinan" },
    { number: 3, name: "Ali 'Imran", english: "Family of Imran", ayahs: 200, type: "Medinan" },
    { number: 4, name: "An-Nisa", english: "The Women", ayahs: 176, type: "Medinan" },
    { number: 5, name: "Al-Ma'idah", english: "The Table Spread", ayahs: 120, type: "Medinan" },
    { number: 6, name: "Al-An'am", english: "The Cattle", ayahs: 165, type: "Meccan" },
    { number: 7, name: "Al-A'raf", english: "The Heights", ayahs: 206, type: "Meccan" },
    { number: 8, name: "Al-Anfal", english: "The Spoils of War", ayahs: 75, type: "Medinan" },
    { number: 9, name: "At-Tawbah", english: "The Repentance", ayahs: 129, type: "Medinan" },
    { number: 10, name: "Yunus", english: "Jonah", ayahs: 109, type: "Meccan" },
    { number: 11, name: "Hud", english: "Hud", ayahs: 123, type: "Meccan" },
    { number: 12, name: "Yusuf", english: "Joseph", ayahs: 111, type: "Meccan" },
    { number: 13, name: "Ar-Ra'd", english: "The Thunder", ayahs: 43, type: "Medinan" },
    { number: 14, name: "Ibrahim", english: "Abraham", ayahs: 52, type: "Meccan" },
    { number: 15, name: "Al-Hijr", english: "The Rocky Tract", ayahs: 99, type: "Meccan" },
    { number: 16, name: "An-Nahl", english: "The Bee", ayahs: 128, type: "Meccan" },
    { number: 17, name: "Al-Isra", english: "The Night Journey", ayahs: 111, type: "Meccan" },
    { number: 18, name: "Al-Kahf", english: "The Cave", ayahs: 110, type: "Meccan" },
    { number: 19, name: "Maryam", english: "Mary", ayahs: 98, type: "Meccan" },
    { number: 20, name: "Ta-Ha", english: "Ta-Ha", ayahs: 135, type: "Meccan" },
    { number: 21, name: "Al-Anbya", english: "The Prophets", ayahs: 112, type: "Meccan" },
    { number: 22, name: "Al-Hajj", english: "The Pilgrimage", ayahs: 78, type: "Medinan" },
    { number: 23, name: "Al-Mu'minun", english: "The Believers", ayahs: 118, type: "Meccan" },
    { number: 24, name: "An-Nur", english: "The Light", ayahs: 64, type: "Medinan" },
    { number: 25, name: "Al-Furqan", english: "The Criterion", ayahs: 77, type: "Meccan" },
    { number: 26, name: "Ash-Shu'ara", english: "The Poets", ayahs: 227, type: "Meccan" },
    { number: 27, name: "An-Naml", english: "The Ant", ayahs: 93, type: "Meccan" },
    { number: 28, name: "Al-Qasas", english: "The Stories", ayahs: 88, type: "Meccan" },
    { number: 29, name: "Al-Ankabut", english: "The Spider", ayahs: 69, type: "Meccan" },
    { number: 30, name: "Ar-Rum", english: "The Romans", ayahs: 60, type: "Meccan" },
    { number: 31, name: "Luqman", english: "Luqman", ayahs: 34, type: "Meccan" },
    { number: 32, name: "As-Sajdah", english: "The Prostration", ayahs: 30, type: "Meccan" },
    { number: 33, name: "Al-Ahzab", english: "The Combined Forces", ayahs: 73, type: "Medinan" },
    { number: 34, name: "Saba", english: "Sheba", ayahs: 54, type: "Meccan" },
    { number: 35, name: "Fatir", english: "Originator", ayahs: 45, type: "Meccan" },
    { number: 36, name: "Ya-Sin", english: "Ya Sin", ayahs: 83, type: "Meccan" },
    { number: 37, name: "As-Saffat", english: "Those Who Set The Ranks", ayahs: 182, type: "Meccan" },
    { number: 38, name: "Sad", english: "The Letter \"Saad\"", ayahs: 88, type: "Meccan" },
    { number: 39, name: "Az-Zumar", english: "The Troops", ayahs: 75, type: "Meccan" },
    { number: 40, name: "Ghafir", english: "The Forgiver", ayahs: 85, type: "Meccan" },
    { number: 41, name: "Fussilat", english: "Explained in Detail", ayahs: 54, type: "Meccan" },
    { number: 42, name: "Ash-Shura", english: "The Consultation", ayahs: 53, type: "Meccan" },
    { number: 43, name: "Az-Zukhruf", english: "The Ornaments of Gold", ayahs: 89, type: "Meccan" },
    { number: 44, name: "Ad-Dukhan", english: "The Smoke", ayahs: 59, type: "Meccan" },
    { number: 45, name: "Al-Jathiyah", english: "The Crouching", ayahs: 37, type: "Meccan" },
    { number: 46, name: "Al-Ahqaf", english: "The Wind-Curved Sandhills", ayahs: 35, type: "Meccan" },
    { number: 47, name: "Muhammad", english: "Muhammad", ayahs: 38, type: "Medinan" },
    { number: 48, name: "Al-Fath", english: "The Victory", ayahs: 29, type: "Medinan" },
    { number: 49, name: "Al-Hujurat", english: "The Rooms", ayahs: 18, type: "Medinan" },
    { number: 50, name: "Qaf", english: "The Letter \"Qaf\"", ayahs: 45, type: "Meccan" },
    { number: 51, name: "Ad-Dhariyat", english: "The Winnowing Winds", ayahs: 60, type: "Meccan" },
    { number: 52, name: "At-Tur", english: "The Mount", ayahs: 49, type: "Meccan" },
    { number: 53, name: "An-Najm", english: "The Star", ayahs: 62, type: "Meccan" },
    { number: 54, name: "Al-Qamar", english: "The Moon", ayahs: 55, type: "Meccan" },
    { number: 55, name: "Ar-Rahman", english: "The Beneficent", ayahs: 78, type: "Medinan" },
    { number: 56, name: "Al-Waqi'ah", english: "The Inevitable", ayahs: 96, type: "Meccan" },
    { number: 57, name: "Al-Hadid", english: "The Iron", ayahs: 29, type: "Medinan" },
    { number: 58, name: "Al-Mujadila", english: "The Pleading Woman", ayahs: 22, type: "Medinan" },
    { number: 59, name: "Al-Hashr", english: "The Exile", ayahs: 24, type: "Medinan" },
    { number: 60, name: "Al-Mumtahanah", english: "She That Is To Be Examined", ayahs: 13, type: "Medinan" },
    { number: 61, name: "As-Saff", english: "The Ranks", ayahs: 14, type: "Medinan" },
    { number: 62, name: "Al-Jumu'ah", english: "The Congregation, Friday", ayahs: 11, type: "Medinan" },
    { number: 63, name: "Al-Munafiqun", english: "The Hypocrites", ayahs: 11, type: "Medinan" },
    { number: 64, name: "At-Taghabun", english: "The Mutual Disillusion", ayahs: 18, type: "Medinan" },
    { number: 65, name: "At-Talaq", english: "The Divorce", ayahs: 12, type: "Medinan" },
    { number: 66, name: "At-Tahrim", english: "The Prohibition", ayahs: 12, type: "Medinan" },
    { number: 67, name: "Al-Mulk", english: "The Sovereignty", ayahs: 30, type: "Meccan" },
    { number: 68, name: "Al-Qalam", english: "The Pen", ayahs: 52, type: "Meccan" },
    { number: 69, name: "Al-Haqqah", english: "The Reality", ayahs: 52, type: "Meccan" },
    { number: 70, name: "Al-Ma'arij", english: "The Ascending Stairways", ayahs: 44, type: "Meccan" },
    { number: 71, name: "Nuh", english: "Noah", ayahs: 28, type: "Meccan" },
    { number: 72, name: "Al-Jinn", english: "The Jinn", ayahs: 28, type: "Meccan" },
    { number: 73, name: "Al-Muzzammil", english: "The Enshrouded One", ayahs: 20, type: "Meccan" },
    { number: 74, name: "Al-Muddaththir", english: "The Cloaked One", ayahs: 56, type: "Meccan" },
    { number: 75, name: "Al-Qiyamah", english: "The Resurrection", ayahs: 40, type: "Meccan" },
    { number: 76, name: "Al-Insan", english: "The Man", ayahs: 31, type: "Medinan" },
    { number: 77, name: "Al-Mursalat", english: "The Emissaries", ayahs: 50, type: "Meccan" },
    { number: 78, name: "An-Naba", english: "The Tidings", ayahs: 40, type: "Meccan" },
    { number: 79, name: "An-Nazi'at", english: "Those Who Drag Forth", ayahs: 46, type: "Meccan" },
    { number: 80, name: "Abasa", english: "He Frowned", ayahs: 42, type: "Meccan" },
    { number: 81, name: "At-Takwir", english: "The Overthrowing", ayahs: 29, type: "Meccan" },
    { number: 82, name: "Al-Infitar", english: "The Cleaving", ayahs: 19, type: "Meccan" },
    { number: 83, name: "Al-Mutaffifin", english: "The Defrauding", ayahs: 36, type: "Meccan" },
    { number: 84, name: "Al-Inshiqaq", english: "The Sundering", ayahs: 25, type: "Meccan" },
    { number: 85, name: "Al-Buruj", english: "The Mansions of the Stars", ayahs: 22, type: "Meccan" },
    { number: 86, name: "At-Tariq", english: "The Morning Star", ayahs: 17, type: "Meccan" },
    { number: 87, name: "Al-A'la", english: "The Most High", ayahs: 19, type: "Meccan" },
    { number: 88, name: "Al-Ghashiyah", english: "The Overwhelming", ayahs: 26, type: "Meccan" },
    { number: 89, name: "Al-Fajr", english: "The Dawn", ayahs: 30, type: "Meccan" },
    { number: 90, name: "Al-Balad", english: "The City", ayahs: 20, type: "Meccan" },
    { number: 91, name: "Ash-Shams", english: "The Sun", ayahs: 15, type: "Meccan" },
    { number: 92, name: "Al-Layl", english: "The Night", ayahs: 21, type: "Meccan" },
    { number: 93, name: "Ad-Duhaa", english: "The Morning Hours", ayahs: 11, type: "Meccan" },
    { number: 94, name: "Ash-Sharh", english: "The Relief", ayahs: 8, type: "Meccan" },
    { number: 95, name: "At-Tin", english: "The Fig", ayahs: 8, type: "Meccan" },
    { number: 96, name: "Al-Alaq", english: "The Clot", ayahs: 19, type: "Meccan" },
    { number: 97, name: "Al-Qadr", english: "The Power", ayahs: 5, type: "Meccan" },
    { number: 98, name: "Al-Bayyinah", english: "The Clear Proof", ayahs: 8, type: "Medinan" },
    { number: 99, name: "Az-Zalzalah", english: "The Earthquake", ayahs: 8, type: "Medinan" },
    { number: 100, name: "Al-Adiyat", english: "The Courser", ayahs: 11, type: "Meccan" },
    { number: 101, name: "Al-Qari'ah", english: "The Calamity", ayahs: 11, type: "Meccan" },
    { number: 102, name: "At-Takathur", english: "The Rivalry in World Increase", ayahs: 8, type: "Meccan" },
    { number: 103, name: "Al-Asr", english: "The Declining Day", ayahs: 3, type: "Meccan" },
    { number: 104, name: "Al-Humazah", english: "The Traducer", ayahs: 9, type: "Meccan" },
    { number: 105, name: "Al-Fil", english: "The Elephant", ayahs: 5, type: "Meccan" },
    { number: 106, name: "Quraysh", english: "Quraysh", ayahs: 4, type: "Meccan" },
    { number: 107, name: "Al-Ma'un", english: "The Small Kindnesses", ayahs: 7, type: "Meccan" },
    { number: 108, name: "Al-Kawthar", english: "The Abundance", ayahs: 3, type: "Meccan" },
    { number: 109, name: "Al-Kafirun", english: "The Disbelievers", ayahs: 6, type: "Meccan" },
    { number: 110, name: "An-Nasr", english: "The Divine Support", ayahs: 3, type: "Medinan" },
    { number: 111, name: "Al-Masad", english: "The Palm Fiber", ayahs: 5, type: "Meccan" },
    { number: 112, name: "Al-Ikhlas", english: "The Sincerity", ayahs: 4, type: "Meccan" },
    { number: 113, name: "Al-Falaq", english: "The Daybreak", ayahs: 5, type: "Meccan" },
    { number: 114, name: "An-Nas", english: "Mankind", ayahs: 6, type: "Meccan" }
]
